"""JWT authentication generation for FastAPI backend."""
from __future__ import annotations

import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...parsers.models import DoqlSpec


def gen_auth(spec: DoqlSpec) -> str:
    """Generate JWT authentication module."""
    role_names = [r.name for r in (spec.roles or [])]
    # Ensure "user" is always an available fallback role
    if "user" not in role_names:
        role_names.append("user")
    roles_enum = ", ".join(f'"{r}"' for r in role_names)

    # Reuse a domain User only when it implements the authentication contract.
    user_entity = next((entity for entity in spec.entities if entity.name == "User"), None)
    user_fields = {field.name for field in user_entity.fields} if user_entity else set()
    has_auth_user_entity = {"username", "email", "hashed_password", "role"} <= user_fields

    if has_auth_user_entity:
        _umd = "from models import User as AuthUser"
    else:
        # A domain entity named User may describe a person without login
        # credentials. Keep authentication records in a separate table so the
        # generated ORM metadata remains valid and the two concepts do not
        # accidentally share an incompatible schema.
        _umd = (
            "class AuthUser(Base):\n"
            '    __tablename__ = "auth_users"\n'
            "    id = Column(String(36), primary_key=True)\n"
            "    username = Column(String(255), unique=True, nullable=False)\n"
            "    email = Column(String(255), unique=True, nullable=True)\n"
            "    hashed_password = Column(String(255), nullable=False)\n"
            '    role = Column(String(64), default="user")\n'
            "    created_at = Column(DateTime, default=datetime.now)"
        )
    # Pre-indent to match the template's 8-space indentation so
    # textwrap.dedent keeps all lines aligned.
    user_model_def = textwrap.indent(_umd, "        ")

    return textwrap.dedent(f'''\
        """JWT authentication — generated by doql."""
        import os
        from datetime import datetime, timedelta, timezone
        from typing import Optional

        from fastapi import APIRouter, Depends, HTTPException, status
        from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
        from pydantic import BaseModel
        from sqlalchemy import Column, String, DateTime
        from sqlalchemy.orm import Session
        from jose import JWTError, jwt
        from passlib.context import CryptContext

        from database import Base, get_db
{user_model_def}

        # Backward-compatible public name for generated consumers.
        User = AuthUser

        SECRET_KEY = os.getenv("JWT_SECRET", "change-me-in-production")
        ALGORITHM = "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 8  # 8 hours

        ROLES = [{roles_enum}]

        pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
        oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login")
        router = APIRouter(prefix="/auth", tags=["auth"])


        class Token(BaseModel):
            access_token: str
            token_type: str = "bearer"


        class UserCreate(BaseModel):
            username: str
            password: str
            email: Optional[str] = None
            role: str = "user"


        class UserResponse(BaseModel):
            model_config = {{"from_attributes": True}}
            id: str
            username: str
            email: Optional[str] = None
            role: str


        def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
            to_encode = data.copy()
            expire = datetime.now(timezone.utc) + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
            to_encode.update({{"exp": expire}})
            return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


        def get_current_user(token: str = Depends(oauth2_scheme), db: Session = Depends(get_db)) -> AuthUser:
            credentials_exception = HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid authentication credentials",
                headers={{"WWW-Authenticate": "Bearer"}},
            )
            try:
                payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
                user_id: str = payload.get("sub")
                if user_id is None:
                    raise credentials_exception
            except JWTError:
                raise credentials_exception
            user = db.query(AuthUser).filter(AuthUser.id == user_id).first()
            if user is None:
                raise credentials_exception
            return user


        def require_role(*allowed_roles: str):
            def checker(current_user: AuthUser = Depends(get_current_user)):
                if current_user.role not in allowed_roles:
                    raise HTTPException(status_code=403, detail="Insufficient permissions")
                return current_user
            return checker


        @router.post("/register", response_model=UserResponse, status_code=201)
        def register(data: UserCreate, db: Session = Depends(get_db)):
            import uuid
            existing = db.query(AuthUser).filter(AuthUser.username == data.username).first()
            if existing:
                raise HTTPException(400, "Username already taken")
            user = AuthUser(
                id=str(uuid.uuid4()),
                username=data.username,
                email=data.email,
                hashed_password=pwd_context.hash(data.password),
                role=data.role if data.role in ROLES else "user",
            )
            db.add(user)
            db.commit()
            db.refresh(user)
            return user


        @router.post("/login", response_model=Token)
        def login(form: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
            user = db.query(AuthUser).filter(AuthUser.username == form.username).first()
            if not user or not pwd_context.verify(form.password, user.hashed_password):
                raise HTTPException(401, "Incorrect username or password")
            token = create_access_token({{"sub": user.id, "role": user.role}})
            return {{"access_token": token}}


        @router.get("/me", response_model=UserResponse)
        def me(current_user: AuthUser = Depends(get_current_user)):
            return current_user
    ''')
